# Generated by Django 3.2.25 on 2024-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
